### ISSUE TITLE
How can i insert images?

### ISSUE THREAD

**Issue by damianoazzolini** [PaulBrownMagic/lpn#4]
I'm translating [chapter 3](http://www.learnprolognow.org/lpnpage.php?pagetype=html&pageid=lpn-htmlse9) of learn prolog now. It has several images, how can i add them into the code? 
P.s. as soon as i finish a will push a PR.

**Comment by nicoabie** [comment]
Hi @damianoazzolini, first of all thanks for contributing.
You can create and images folder inside of www/static and then use termarized html like `img(src('/static/images/image.png'),[])` should do the trick.

**Comment by PaulBrownMagic** [comment]
Thank you @damianoazzolini!

I've pushed a html component, so you can use `\diagram(Source, Alt)`.

Source is concatenated onto `'/static/images/'`, so for chapter2 I've added some images to `/static/images/chapter2/`, such as `/static/images/chapter2/diagram1.png`. So I can put in my content: `\diagram('chapter2/diagram1.png', "The search tree with head expanded")`

See [Chapter 2, Section2, line 21](https://github.com/PaulBrownMagic/lpn/blob/master/www/book/chapters/chapter2/section2.lgt) for an example of use, including an image from the [chapter2 images folder](https://github.com/PaulBrownMagic/lpn/tree/master/www/static/images/chapter2).
