### ISSUE TITLE
Faster init/0 implementation

### ISSUE THREAD

**Issue by pmoura** [PaulBrownMagic/lpn#7]
The `init/0` predicate currently defined as:

https://github.com/PaulBrownMagic/lpn/blob/09a818b25ddccd26023e028617d24852e0a04ae5/www/static/pl/mcq.pl#L6-L8

can be rewritten for better performance as:

```logtalk
init :- 
     forall(get_by_type(radio, Input), bind_click(Input)).
```

**Comment by PaulBrownMagic** [comment]
Unfortunately that predicate is interpreted by Tau Prolog, which doesn't yet have `forall/2`. Hopefully sometime in the future!

**Comment by pmoura** [comment]
I contributed a definition for the de facto standard `forall/2` predicate to Tau Prolog. It's there:

```
commit 703b016ce64ffde744b08fa01bf4d603e54ef3a5
Merge: 30e095a a48b819
Author: José Antonio Riaza Valverde <riazavalverde@gmail.com>
Date:   Wed Jul 11 13:09:51 2018 +0200

    Merge pull request #34 from pmoura/add_forall_predicate
    
    WIP: Add de facto standard forall/2 predicate
```

Maybe the documentation still doesn't reflect it?

**Comment by PaulBrownMagic** [comment]
You're right, it was just missing from the documentation.
